import Head from 'next/head'
import type { NextPage } from 'next'
import { HearIcon } from '@/assets/icons'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HearIcon />
      </main>
    </>
  )
}

export default Home
